version: '2.1'

services:
  softhsm:
    image: dahoba/softhsm-proxy
    environment:
      PKCS11_DAEMON_SOCKET: "tcp://0.0.0.0:5657"
    ports:
      - "5657:5657"
  app:
    image: dahoba/tomcat-pcks11-proxy
    build: .    
#    volumes:
#      - "/path/to/wepapp-1.0.0.war:/usr/local/tomcat/webapps/wepapp-1.0.0.war"


#      - "/path/to/logs:/usr/local/tomcat/logs"
    environment:
      PKCS11_PROXY_SOCKET: "tcp://softhsm:5657"
    ports:
      - "8080:8080"
    depends_on:
      - softhsm
